-- Update password for admin1
-- Plain password: Admin@123
-- BCrypt hash generated by PasswordHashGenerator

UPDATE users
SET password = '$2a$10$EEtmEYDegIrpzRCHy2U7QOVH188xLxwUHVVw6pjar079w6o9QQ1AK'
WHERE username = 'admin1';
